spring.application.name=official-website-backend
server.port=8080
app.storage.upload-dir=./data/uploads
app.storage.metadata-file=./data/downloads.json
springdoc.swagger-ui.path=/swagger-ui.html
spring.servlet.multipart.max-file-size=300MB
spring.servlet.multipart.max-request-size=350MB

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/official_website?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:89dfu*#$ewr87l}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always

app.security.admin-username=${APP_ADMIN_USERNAME:administrator}
app.security.admin-password=${APP_ADMIN_PASSWORD:admin123}
